-- models/marts/dim_customer.sql

{{
    config(materialized = 'table')
}}

SELECT
    dbt_scd_id          AS customer_sk,      -- surrogate key (auto-generated by dbt)
    customer_id,                              -- natural key (keep for source joins)

    customer_name,
    address,
    nation_id,
    phone,
    account_balance,
    market_segment,
    comment,

    dbt_valid_from      AS valid_from,
    dbt_valid_to        AS valid_to,
    dbt_valid_to IS NULL AS is_current

FROM {{ ref('snap_customer') }}              -- reads from snapshot